# Generated by Django 5.2.9 on 2025-12-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assets',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='average_monthly_spend',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(default='2000-01-01', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='credit_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='financial_products',
            field=models.ManyToManyField(blank=True, related_name='subscribed_users', to='products.product', verbose_name='가입한 금융상품'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', '남성'), ('1', '여성')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='test_nickname', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tender',
            field=models.CharField(blank=True, choices=[('1', '매우보수적'), ('2', '보수적'), ('3', '보통'), ('4', '공격적'), ('5', '매우공격적')], null=True),
        ),
    ]
