# Generated by Django 5.2.9 on 2025-12-23 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_badge_userbadge_userfollow"),
        ("challenges", "0003_moathonlike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbadge",
            name="moathon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="challenges.moathon",
            ),
        ),
    ]
