# Generated by Django 5.2.9 on 2025-12-14 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.CharField(max_length=20, unique=True)),
                ('kor_co_nm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('DEPOSIT', '정기예금'), ('SAVING', '적금')], max_length=10)),
                ('fin_prdt_cd', models.CharField(max_length=50)),
                ('fin_prdt_nm', models.CharField(max_length=200)),
                ('dcls_month', models.CharField(blank=True, max_length=6)),
                ('dcls_strt_day', models.CharField(blank=True, max_length=8)),
                ('dcls_end_day', models.CharField(blank=True, max_length=8)),
                ('fin_co_subm_day', models.CharField(blank=True, max_length=14)),
                ('join_way', models.CharField(blank=True, max_length=200)),
                ('join_member', models.CharField(blank=True, max_length=200)),
                ('join_deny', models.CharField(blank=True, max_length=10)),
                ('spcl_cnd', models.TextField(blank=True)),
                ('etc_note', models.TextField(blank=True)),
                ('mtrt_int', models.TextField(blank=True)),
                ('max_limit', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.bank')),
            ],
            options={
                'unique_together': {('bank', 'product_type', 'fin_prdt_cd')},
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(blank=True, max_length=10)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=20)),
                ('rsrv_type', models.CharField(blank=True, max_length=10)),
                ('rsrv_type_nm', models.CharField(blank=True, max_length=20)),
                ('save_trm', models.CharField(blank=True, max_length=10)),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.product')),
            ],
        ),
    ]
