# Generated by Django 5.2.4 on 2025-12-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='dcls_month',
        ),
        migrations.AddField(
            model_name='productoption',
            name='rsrv_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='productoption',
            name='rsrv_type_nm',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
