# Generated by Django 5.2.9 on 2025-12-19 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('target_amount', models.PositiveBigIntegerField()),
                ('start_amount', models.PositiveBigIntegerField()),
                ('term_months', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('purpose', models.CharField(choices=[('GOAL', '목돈 마련'), ('SHORT', '단기 여유자금'), ('SAFE', '안정적 자산 보관'), ('HABIT', '저축 습관 형성'), ('YIELD', '이자 극대화')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moathons', to='products.productoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_moathon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'title'), name='uniq_moathon_title_per_user')],
            },
        ),
    ]
