# Generated by Django 5.2.9 on 2025-12-21 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moathon',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
