# Generated by Django 5.2.9 on 2025-12-21 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoathonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='challenges.moathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moathon_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['moathon', 'created_at'], name='challenges__moathon_ad5c97_idx')],
            },
        ),
    ]
