# Generated by Django 5.2.9 on 2025-12-22 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_moathoncomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoathonLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='challenges.moathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moathon_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['moathon', 'created_at'], name='challenges__moathon_996faf_idx'), models.Index(fields=['user', 'created_at'], name='challenges__user_id_95e18f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'moathon'), name='unique_like_per_user_moathon')],
            },
        ),
    ]
