# Generated by Django 5.2.9 on 2025-12-21 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityAsset',
            fields=[
                ('asset', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommodityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close_last', models.DecimalField(decimal_places=6, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=6, max_digits=20)),
                ('open', models.DecimalField(decimal_places=6, max_digits=20)),
                ('high', models.DecimalField(decimal_places=6, max_digits=20)),
                ('low', models.DecimalField(decimal_places=6, max_digits=20)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='visualizations.commodityasset')),
            ],
        ),
    ]
